name: learnreg1d
dependencies:
  - python=3.8.5
  - pytorch::pytorch=1.6.0  # automatic differentiation
  - conda-forge::cvxpy=1.1.6
  - pip=20.2.3
  - matplotlib=3.3.1
  - pip:
      - -e src

