name: learnreg1d
dependencies:
  - python=3.8.5
  - pytorch::pytorch=1.6.0  # automatic differentiation
  - conda-forge::cvxpy=1.1.7
  - pip=20.2.3
  - matplotlib=3.3.1
  - pymongo=3.11.2
  - mongodb=4.0.3
  - seaborn>=0.11.1
  - pip:
      - -e src
      - cvxpylayers==0.1.4
      - sacred==0.8.2
      - shortuuid



